name: "Initialize Request"
description: "Step 1: Create Milestone, branch, and Request Issues (Start/Completion)"

inputs:
  title:
    description: "Natural language request title"
    required: true
  intent:
    description: "Optional detailed intent or background"
    required: false
  branch_name:
    description: "Optional branch name override (without prefix)"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Initialize Request"
      uses: actions/github-script@v7
      with:
        script: }